### ISSUE TITLE
Alternate download source(s)

### ISSUE THREAD

**Issue by Sakata-MC** [BitCurator/bitcurator#104]
Something that may help to get the project out to people is having a torrent download link  as an option. The extremely slow link on http is frustrating to say the least, especially with it locked down the way it is.

Having a torrent as a suggested distribution would speed up retrieval by several orders of magnitude, and free up resources on the server.

**Comment by kamwoods** [comment]
Closing this issue as it is unrelated to the codebase. Please direct concerns about distribution to the Consortium at https://bitcuratorconsortium.org
